"""Spring 연동 예측 모델 상수."""

from __future__ import annotations

import math

from app.services.classifier import TaskType


MODEL_VERSION = "v2.2.0"

STAGE_EARLY = "EARLY"
STAGE_MAIN_EFFECT = "MAIN_EFFECT"
STAGE_INTERACTION = "INTERACTION"

VALID_DIFFICULTIES = {"EASY", "NORMAL", "MEDIUM", "HARD", "UNKNOWN"}
VALID_TASK_TYPES = {task_type.value for task_type in TaskType}

EARLY_LOG_MIN = -0.5
EARLY_LOG_MAX = 0.7
MAIN_EFFECT_LOG_MIN = -0.7
MAIN_EFFECT_LOG_MAX = 0.9
INTERACTION_LOG_MIN = -0.8
INTERACTION_LOG_MAX = 1.0
OBSERVATION_LOG_MIN = math.log(1 / 3)
OBSERVATION_LOG_MAX = math.log(4.0)

SHRINKAGE_DENOMINATOR = 10
INTERACTION_COUNT_THRESHOLD = 20
SYSTEM_PRIOR_SHRINKAGE_DENOMINATOR = 50
EARLY_ETA_GLOBAL = 0.10
EARLY_ETA_TYPE = 0.15
MAIN_EFFECT_RETRAIN_INTERVAL = 10
INTERACTION_RETRAIN_INTERVAL = 50
